all: my_solution.out site_solution.out

my_solution.out: my_solution.cpp
	g++ -std=c++17 -omy_solution.out my_solution.cpp

site_solution.out: site_solution.cpp
	g++ -std=c++17 -osite_solution.out site_solution.cpp

clean:
	rm *.out 